### ISSUE TITLE
FIX the Navbar and make it responsive 

### ISSUE THREAD

**Issue by sahhoArjun097** [ChandelAnish/hireHUB-website#18]
i can fix the navbar add button in it to make it attractive .

![image](https://github.com/user-attachments/assets/3b7df9ed-0b11-4068-8487-a34b36d7c7d6)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by Virenishere** [comment]
Hey! @ChandelAnish I will make this navbar responsive for all screen attaching the hamburger menulist 

please assign this task to me for GSSoC 2024 Extd.

Thanks 

Virender Prasad

**Comment by sahhoArjun097** [comment]
please assign me this issue i would like to work on it

**Comment by ChandelAnish** [comment]
similar issue already raised #3

**Comment by Virenishere** [comment]
Thanks for letting me know @ChandelAnish

**Comment by sahhoArjun097** [comment]
@ChandelAnish  i will make the navbar responsive and and style the button and provide hover and animation effect  to enhance the view
