### ISSUE TITLE
Enhancement of Navbar/Header

### ISSUE THREAD

**Issue by Shariq2003** [ChandelAnish/hireHUB-website#3]
The Navbar of the Website is looking to weard, I can enhance it by adding some CSS that makes it better and User attractive.

@Akash-1611 @aditripathi1357 @ChandelAnish @adityranjan790  
Please assign this to me.

![image](https://github.com/user-attachments/assets/96d3556c-36cc-4515-8c20-bf0cbfa3d9a8)

**Comment by ChandelAnish** [comment]
similar issue already raised

**Comment by Shariq2003** [comment]
No, no one raised, I have checked before then raise the issue.
Please check sir
Even I raises the issue first

**Comment by ChandelAnish** [comment]
#5
