### ISSUE TITLE
Adding enhanced UI for the features 

### ISSUE THREAD

**Issue by aditiverma-21** [ChandelAnish/hireHUB-website#32]
![image](https://github.com/user-attachments/assets/249f2185-0e65-408d-b349-b1986bd9edc0)
I want to improve the UI for this section for more aesthetic and clear UI.

**Comment by ChandelAnish** [comment]
@aditiverma-21 you are assigned

**Comment by aditiverma-21** [comment]
Thank you

**Comment by aditiverma-21** [comment]
@ChandelAnish Please add level and labels
