### ISSUE TITLE
Toggle feature to the section

### ISSUE THREAD

**Issue by aditiverma-21** [ChandelAnish/hireHUB-website#33]
![image](https://github.com/user-attachments/assets/0340c18c-f40a-47d6-8a22-a248b1574789)
The effect in this section is overdone and not optimistic. I want make the transition more smooth and attractic

**Comment by ChandelAnish** [comment]
@aditiverma-21 you are assigned

**Comment by aditiverma-21** [comment]
Thank you.

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/78a19dd0-c802-4eaa-8107-b82b489fadfe

@ChandelAnish Please check this effect I have added

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/0d9f04e0-eed1-4171-8e15-e7509ee9009d
