### ISSUE TITLE
Enhancement of Login Page

### ISSUE THREAD

**Issue by Shariq2003** [ChandelAnish/hireHUB-website#4]
The login page is also too weard as their is no placeholders in the fields also the UI is not good.
@Akash-1611 @aditripathi1357 @ChandelAnish @adityranjan790 

Please assign this task to me.

![image](https://github.com/user-attachments/assets/f6c2a701-3543-45e6-97f7-8a7bfec7f9a3)

**Comment by Shariq2003** [comment]
@aditripathi1357 @ChandelAnish please add label of level for this issue and assign this to me so that I can start working on it.

**Comment by Shariq2003** [comment]
@ChandelAnish please add label of level to this and assign this to me

**Comment by ChandelAnish** [comment]
@Shariq2003 you will ensure the UI is responsive for all devices, add placeholders, and enhance the UI while strictly adhering to the current color scheme and code of conduct.

**Comment by Shariq2003** [comment]
sure, thanks for assigning

**Comment by Shariq2003** [comment]
@ChandelAnish I am facing issues while setting up the project.
I have forked the repo, clone that, create a new branch and then when I run npm I, I faced this ,
```
PS C:\Users\ShariqSD\Desktop\GSSOC\hireHUB-website> npm i
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\ShariqSD\Desktop\GSSOC\hireHUB-website/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ShariqSD\Desktop\GSSOC\hireHUB-website\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: C:\Users\ShariqSD\AppData\Local\npm-cache\_logs\2024-10-02T10_43_22_238Z-debug-0.log
PS C:\Users\ShariqSD\Desktop\GSSOC\hireHUB-website> 
```
I am trying to fixs this, but not succeed please help,.....

**Comment by Shariq2003** [comment]
> first run : cd server
> 
> read the installation process from README.md file [https://github.com/ChandelAnish/hireHUB-website/blob/master/README.md](url) or can use this docker image to setup your environment [https://hub.docker.com/r/chandelanish/hirehub-server](url)

No Sir, I am facing issue in setting up the Frontend, the backend has start successfully,

**Comment by Slambot01** [comment]
@ChandelAnish can you please assign me this issue?

**Comment by garimabhayanaa** [comment]
can i please work on this issue?

**Comment by jjf2009** [comment]
@ChandelAnish Kindly assign me this issue 
![Screenshot 2024-10-07 at 22-17-52 Frontent Mentor](https://github.com/user-attachments/assets/f069da54-c8fe-4869-8932-b2639fa677b5)
![Screenshot 2024-10-07 at 22-18-01 Frontent Mentor](https://github.com/user-attachments/assets/018c2ae5-0ce6-4256-ada2-9307737c6860)
![Screenshot 2024-10-07 at 22-18-16 Frontent Mentor](https://github.com/user-attachments/assets/18994e8c-6156-42d6-a44c-1e9f27c34993)
I have Build such login pages before add level-2 label please

**Comment by Shantanu675** [comment]
Can you assign me this issue. I will fix in few time I have great experience in web dev and I worked on similar issues before

**Comment by Shariq2003** [comment]
> @Shariq2003 you will ensure the UI is responsive for all devices, add placeholders, and enhance the UI while strictly adhering to the current color scheme and code of conduct.

@ChandelAnish I really sorry for not responding to this issue, just stuck in the backlogs, now working on the issue.
Will Raise the PR by Tomorrow morning
