### ISSUE TITLE
[Feature enhancement] : ✨ we can add dark mode feature ✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ChandelAnish/hireHUB-website#40]
adding a dark mode feature can help the user choose his preferred background theme, can u please assign me this so i can work on this feature.

**Comment by ChandelAnish** [comment]
#7 addresses same issue

**Comment by T-Rahul-prabhu-38** [comment]
oh didnt see that

**Comment by T-Rahul-prabhu-38** [comment]
but sir its been 2 days since that was assigned to them, can i try? i can do it in 20 mins.

**Comment by T-Rahul-prabhu-38** [comment]
@ChandelAnish  sir, #7 was assigned 3 days back , if there inst any response from them , can i work on it? i can fix it within 1 hr.

**Comment by ChandelAnish** [comment]
sure, comment in #7
