### ISSUE TITLE
Adding Hovering effects to the Nav Bar

### ISSUE THREAD

**Issue by aditiverma-21** [ChandelAnish/hireHUB-website#56]
![image](https://github.com/user-attachments/assets/2153d44e-0b6e-43fc-ac64-40c3d0e6dad7)
I want to add colours and effects to this nav bar for more attractive UI.

**Comment by Balaji-Ramesh** [comment]
hi.. can you assign this work to me...

**Comment by arpit74170** [comment]
I can fix this issue with the more attractive ui with colours and animation and hover effect,could you please assign this to me??

**Comment by ChandelAnish** [comment]
can you make it responsive ??

**Comment by aditiverma-21** [comment]
@ChandelAnish yes I can link it and make it responsive.

**Comment by arpit74170** [comment]
> I can fix this issue with the more attractive ui with colours and animation and hover effect,could you please assign this to me??



> can you make it responsive ??

Yes

**Comment by ChandelAnish** [comment]
Issue already addressed

**Comment by aditiverma-21** [comment]
@ChandelAnish okay

**Comment by arpit74170** [comment]
Assign this to me!

**Comment by arpit74170** [comment]
Assigned this to me
