### ISSUE TITLE
 Add Hover Effects to Footer Links and Button for Enhanced Interactivity

### ISSUE THREAD

**Issue by sahhoArjun097** [ChandelAnish/hireHUB-website#77]
The current footer section lacks a hover effect on the links and buttons, which can reduce user engagement and interactivity. Adding a hover effect will enhance the user experience by providing visual feedback when users interact with the footer elements.

![Screenshot 2024-10-06 014857](https://github.com/user-attachments/assets/8f5c7065-e953-4115-8be9-ff8574104fa9)

Implement hover effects to improve interaction feedback, ensuring a more dynamic and engaging footer section.

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by ChandelAnish** [comment]
Issue already raised

**Comment by sahhoArjun097** [comment]
you didn't assign any one for this issue  i am styling the footer section elements not making it responsive . 
Please assign me this

**Comment by sahhoArjun097** [comment]
there are no social icons in there i can add them too

**Comment by sahhoArjun097** [comment]
you said issue is raised i didn't see any changes in the footer yet
